### ISSUE TITLE
feature request: support for PDF as image format

### ISSUE THREAD

**Issue by aidanreilly** [dita-semia/org.dita-semia.image-convert#2]
Hi,

Feel free to close or move this ticket if it is not appropriate as an issue. 

I think it would be a nice feature to implement Apache PDFBox as an image renderer for .pdf format images. See here for context: 

https://www.oxygenxml.com/forum/post28766.html#p28766

I may fork and try and implement this myself, but i am not a very strong developer. Let me know what you think

Thanks,

Aidan

**Comment by PStellmann** [comment]
Hi Aidan,

I think your request fits nicely into this plugin. And the programming should not be that hard.

The implementatin steps would probably be
- dublicate lines 42 to 80 in file preprocess.image-convert.xml 
- change <rasterize> to a call of PDFToImage
- change the regexp to pdf instead of svg
- add the PDFBox jar file to the classpath

And for testing add in transtype-samples/xhtml-png/dita2xhtml-png.xsl another template to change references to pdf images to png as well.

Let me know if you're gonna try to implement it or when you need further assistance.

I might give it a try on my own, but not within the next few days...

Patrik

**Comment by aidanreilly** [comment]
Thanks Patrik for the info, I will do this and submit a pull request :) Hopefully in the next few days.

**Comment by aidanreilly** [comment]
Hi Patrik, started looking at this. I'm unsure about how to proceed with the rasterizer taskdef. Do I need to produce a new version of RasterizerTask.jar for pdf images?

https://github.com/aidanreilly/org.dita-semia.image-convert/blob/master/preprocess.image-convert.xml#L12

**Comment by aidanreilly** [comment]
ah. ok. I need to use org.apache.pdfbox.tools.PDFToImage

**Comment by aidanreilly** [comment]
I must be doing something silly: 

Error: taskdef class org.apache.pdfbox.tools.PDFToImage cannot be found
 using the classloader AntClassLoader[]

Any ideas?

**Comment by PStellmann** [comment]
I think to use taskdef you need a java class that implements the appropriate ant task interface. But PDFToImage is a simple stand-alone application. So remove the taskdef and instead of <rasterizerpdf> use <java ...> there and call the java class directly.

**Comment by aidanreilly** [comment]
You mean something like this? https://github.com/aidanreilly/org.dita-semia.image-convert/blob/master/preprocess.image-convert.xml#L12

I get an error still :( Sorry, my java is poor...

**Comment by PStellmann** [comment]
I managed to make it work to some extent: https://github.com/dita-semia/org.dita-semia.image-convert/blob/pdfbox/preprocess.image-convert.xml#L100

But I could not manage to pass any options. Placing them after the filename they are ignores. Placing them before I get an error: 
>      [java] Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
>      [java] 	at java.lang.String.substring(Unknown Source)
>      [java] 	at org.apache.pdfbox.tools.PDFToImage.main(PDFToImage.java:210)

But maybe this is a starting point for you...

**Comment by aidanreilly** [comment]
Thank you Patrik for your help thus far. Hope you had a good Christmas break. I have got this working to a degree, however it is not satisfactory. The pdf-box jar does not accept parameters. Calling the java jar at the command line works just fine: 

java -jar C:\dita-ot-2.5.4-ixiasoft\plugins\org.dita-semia.image-convert\lib\pdfbox-app-2.0.13.jar PDFToImage C:\dita-ot-2.5.4-ixiasoft\plugins\org.dita-semia.image-convert\test\figure-4.pdf -page 1 -dpi 96 -imageType png

Implementing it as you suggest and the parameters get ignored. Very odd. So perhaps an issue with the OT itself?  I am using dita-ot-2.5.4. The jar does produce an image however, a jpg. And  I was able to add another processing step to account for the pdf image file naming in the output. So It works, but does not accept image parameters. I will investigate the source code and see if there is anything obvious that could be changed and rebuild the jar.

**Comment by PStellmann** [comment]
I'm pretty sure this can't be an issue with OT since it is not involved in this step. It is purely ant + pdfbox. An idea might be to ask for help on pdfbox forum or whatever there is...

**Comment by aidanreilly** [comment]
I got this working with some help from the pdfbox group. Rookie error, I was passing parameters incorrectly. This is how it should work. My next step is to figure out how to also apply the conversion processing to keydef images that are referenced in ditamaps. thanks for your help thus far Patrik!  

                                <java classname="org.apache.pdfbox.tools.PDFToImage" fork="true"
                                    failonerror="true">
                                    <classpath>
                                        <pathelement location="lib/pdfbox-app-2.0.13.jar"/>
                                    </classpath>
                                    <arg value="${output.dir}/@{src-filename}"/>
                                    <arg value="-page 1"/>
                                    <arg value="-dpi"/>
                                    <arg value="${dita-semia.image-convert.dpi}"/>
                                    <arg value="-imageType"/>
                                    <arg value="${dita-semia.image-convert.dest-format}"/>
                                </java>

**Comment by aidanreilly** [comment]
OK, this was easier than I thought. 

to process the following:
      `<keydef href="Figure-3.svg" keys="Figure-3" format="image"/> `

the format must be set to image, based on: https://github.com/dita-ot/dita-ot/issues/1988#issuecomment-211759214 

This code picks it up in the xhtml-png conversion: 

	
	<xsl:template match="*[contains(@class, ' map/keydef ')]/@href[matches(lower-case(.), '\.pdf$')]">
		<xsl:attribute name="src" select="replace(., '\.pdf$', '1.png')"/>
	</xsl:template>
